### ISSUE TITLE
点开效果没有盖住 导航条和tabBar

### ISSUE THREAD

**Issue by CoderLineChan** [angelen10/PhotoPreviewer#2]

**Comment by angelen10** [comment]
@CoderLineChan 本意就是没有盖住导航条和 tabBar 的，因为它是被添加到当前控制器的 self.view 上的，而且我添加到当前控制器的 self.view 上的好处是：我能够继续长按弹出 UIAlertController 询问是否保存图片之类的；如果你希望要盖住导航条和 tabBar 的，不要那么麻烦，直接将其添加到 keyWindow 上即可🚀

**Comment by CoderLineChan** [comment]
我是希望两者都可以了，

**Comment by angelen10** [comment]
@CoderLineChan 如果希望两者都可以，我建议的做法是：将它添加到 keyWindow 上，然后长按图片的时候，自定义 alertView 添加到图片上
